all:
  hosts:
    menos:
      ansible_host: 192.168.16.241
      ansible_user: anvil
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  vars:
    deploy_path: /apps/menos
    data_path: /apps/menos/data
